name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type destroy to confirm"
        required: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  TF_IN_AUTOMATION: true

jobs:
  terraform-destroy:
    if: ${{ inputs.confirm_destroy == 'destroy' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::435059220418:role/ronin-github-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy
        run: terraform destroy -input=false -auto-approve